CREATE DATABASE WEVO
GO

CREATE TABLE USUARIO
(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME NVARCHAR(200) NOT NULL,
	CPF BIGINT NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	TELEFONE BIGINT NOT NULL,
	SEXO CHAR(1) NOT NULL,
	DATANASCIMENTO DATE NOT NULL
)
GO
